// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVqDULYGQqi7aO5_LZ376AMasVpg-WRVg',
    appId: '1:846412854830:web:fe743b6dd9840f513a11bf',
    messagingSenderId: '846412854830',
    projectId: 'stl-portal',
    authDomain: 'stl-portal.firebaseapp.com',
    storageBucket: 'stl-portal.appspot.com',
    measurementId: 'G-S9CS010PS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvVo3Ap90ZxTQsWO9d-ZMypW-PLqaCD64',
    appId: '1:846412854830:android:ad230ea5f4a28e963a11bf',
    messagingSenderId: '846412854830',
    projectId: 'stl-portal',
    storageBucket: 'stl-portal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQifWDZQNVuG6bZqgHVUK7CubIDKuKM1U',
    appId: '1:846412854830:ios:3728380b8e5f5f353a11bf',
    messagingSenderId: '846412854830',
    projectId: 'stl-portal',
    storageBucket: 'stl-portal.appspot.com',
    iosClientId: '846412854830-kkjemduuirnkgdtk1umn5jpmani5eg93.apps.googleusercontent.com',
    iosBundleId: 'com.example.stcPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQifWDZQNVuG6bZqgHVUK7CubIDKuKM1U',
    appId: '1:846412854830:ios:3728380b8e5f5f353a11bf',
    messagingSenderId: '846412854830',
    projectId: 'stl-portal',
    storageBucket: 'stl-portal.appspot.com',
    iosClientId: '846412854830-kkjemduuirnkgdtk1umn5jpmani5eg93.apps.googleusercontent.com',
    iosBundleId: 'com.example.stcPortal',
  );
}
